# Generated by Django 3.2 on 2024-08-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256, verbose_name='Название департамента')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя начальника')),
                ('position', models.CharField(max_length=256, verbose_name='Роль')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Зарплата')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия сотрудника')),
                ('position', models.CharField(max_length=256, verbose_name='Роль')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Зарплата')),
                ('birth_date', models.DateField()),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empoyee', to='depart.departament', verbose_name='работники департамента')),
            ],
        ),
        migrations.AddField(
            model_name='departament',
            name='boss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='depart.director', verbose_name='Департамент'),
        ),
    ]
