# Generated by Django 3.2 on 2024-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя начальника'),
            preserve_default=False,
        ),
    ]
