# Generated by Django 3.2 on 2024-08-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0002_director_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='boss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='depart.director', verbose_name='Директор департамента'),
        ),
    ]
