# Generated by Django 3.2 on 2024-08-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0003_alter_departament_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='boss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='depart.director', verbose_name='Директор департамента'),
        ),
    ]
