# Generated by Django 3.2 on 2024-08-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_alter_departament_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boss_of_depart', to='depart.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='departament',
            name='boss',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AddField(
            model_name='directordepart',
            name='depart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departament', to='depart.departament'),
        ),
    ]
