# Generated by Django 3.2 on 2024-08-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0005_auto_20240813_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depart.departament')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя начальника')),
                ('last_name', models.CharField(max_length=200, verbose_name='Имя начальника')),
                ('position', models.CharField(max_length=256, verbose_name='Роль')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Зарплата')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empoyee', to='depart.departament', verbose_name='работники департамента'),
        ),
        migrations.DeleteModel(
            name='DirectorDepart',
        ),
        migrations.AddField(
            model_name='departemp',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depart.director'),
        ),
        migrations.AddField(
            model_name='departemp',
            name='epmloyee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depart.employee'),
        ),
        migrations.AddField(
            model_name='departament',
            name='direct',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='depart.director', verbose_name='Директор департамента'),
            preserve_default=False,
        ),
    ]
