# Generated by Django 3.2 on 2024-08-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0006_auto_20240813_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartEmp',
        ),
    ]
