# Generated by Django 3.2 on 2024-08-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0008_departemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='departament',
            name='direct',
        ),
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empoyee', to='depart.departament', verbose_name='работники департамента'),
        ),
        migrations.DeleteModel(
            name='DepartEmp',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AddField(
            model_name='directordepart',
            name='depart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='depart.departament', verbose_name='Название департамента'),
        ),
        migrations.AddField(
            model_name='directordepart',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boss_of_depart', to='depart.employee', verbose_name='Директор департамента'),
        ),
    ]
