# Generated by Django 3.2 on 2024-08-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0010_alter_employee_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='depart.departament', verbose_name='Pаботник департамента'),
        ),
    ]
